using UnityEngine;

namespace RPG.SceneManagement
{
    
public class GateGuardianControl : MonoBehaviour
{
    //public Scene[] regionsAvailable = ("Sandbox01", "Sandbox02");  // TODO: research proper syntax

        float timeSinceTeleportation = Mathf.Infinity;
        float interactionRadius = 1f;

        GameObject player;
        GameObject gate1;
        GameObject gate2;
        GameObject gate3;

        const float teleportationFrequency = 10f;


        private void Start()
        {
            player = GameObject.FindWithTag("Player");
            gate1 = GameObject.Find("Gate (1)");
            gate2 = GameObject.Find("Gate (2)");
            gate3 = GameObject.Find("Gate (3)");
        }

        private void Update()
        {
            if (DistanceToTarget() <= interactionRadius) { InteractWithPlayer(); }
        }

        private float DistanceToTarget()
        {
            return Vector3.Distance(player.transform.position, transform.position);
        }

        void InteractWithPlayer()
        {
            // NPC welcomes the player and asks what region they want to travel to.
            // the player must choose from a list generated by the games build index
        }

        void ActivateGates()
        {
            timeSinceTeleportation = 0f;
        }
    }
}
